-- require("tmux").setup({
--     -- overwrite default configuration
--     -- here, e.g. to enable default bindings
--     navigation = {
--         -- enables default keybindings (C-hjkl) for normal mode
--         enable_default_keybindings = true,
--     },
--     resize = {
--         -- enables default keybindings (A-hjkl) for normal mode
--         enable_default_keybindings = true,
--     }
-- })
